spring:
  shell.interactive.enabled: true
  main.allow-bean-definition-overriding: true

  messages:
    encoding: cp1251
    basename: library

  jpa:
    database: postgresql
    hibernate.ddl-auto: none

    show-sql: false
    properties.format_sql: true
    properties.hibernate.jdbc.lob.non_contextual_creation: true
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    properties.dialect: org.hibernate.dialect.PostgreSQL95Dialect

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/springdb
    username: spring
    password: password
    initialization-mode: always

  data:
    mongodb:
      uri: mongodb://localhost
      port: 27017
      database: springdb