spring:
  shell.interactive.enabled: true
  #main.allow-bean-definition-overriding: true

  messages:
    encoding: cp1251
    basename: library

  data:
    mongodb:
      uri: mongodb://localhost
      port: 27017
      database: springdb